"""JAX-native TokaMaker port scaffold."""

from tokamaker_jax.assembly import (
    DirichletSystem,
    apply_dirichlet_conditions,
    apply_global_matrix,
    apply_laplace_stiffness_matrix,
    apply_mass_matrix,
    assemble_global_matrix,
    assemble_laplace_stiffness_bcoo,
    assemble_laplace_stiffness_matrix,
    assemble_load_vector,
    assemble_mass_bcoo,
    assemble_mass_matrix,
    boundary_nodes_from_coordinates,
    linear_load_vector,
    solve_dirichlet_system,
)
from tokamaker_jax.benchmarks import (
    BenchmarkResult,
    benchmark_callable,
    benchmark_local_fem_kernel,
    benchmark_seed_equilibrium,
)
from tokamaker_jax.config import CoilConfig, GridConfig, RunConfig, SolverConfig, load_config
from tokamaker_jax.domain import RectangularGrid
from tokamaker_jax.fem import (
    TriangleQuadrature,
    linear_basis,
    linear_basis_gradients,
    linear_mass_matrix,
    linear_stiffness_matrix,
    reference_triangle_nodes,
    triangle_area,
    triangle_jacobian,
    triangle_quadrature,
)
from tokamaker_jax.geometry import (
    Region,
    RegionSet,
    annulus_region,
    polygon_region,
    rectangle_region,
    sample_regions,
)
from tokamaker_jax.mesh import TriMesh, load_gs_mesh, mesh_from_arrays, save_gs_mesh
from tokamaker_jax.plotting import FigureRecipe
from tokamaker_jax.profiles import MU0, gaussian_coil_source, normalized_flux, solovev_source
from tokamaker_jax.solver import (
    EquilibriumSolution,
    apply_operator,
    solve_fixed_boundary,
    solve_from_config,
)
from tokamaker_jax.verification import (
    PoissonConvergenceResult,
    PoissonConvergenceStudy,
    observed_rates,
    poisson_error_metrics,
    run_poisson_convergence_study,
    sine_poisson_exact,
    sine_poisson_forcing,
    solve_sine_poisson,
    unit_square_triangles,
)

__all__ = [
    "BenchmarkResult",
    "CoilConfig",
    "DirichletSystem",
    "EquilibriumSolution",
    "FigureRecipe",
    "GridConfig",
    "MU0",
    "PoissonConvergenceResult",
    "PoissonConvergenceStudy",
    "RectangularGrid",
    "Region",
    "RegionSet",
    "RunConfig",
    "SolverConfig",
    "TriMesh",
    "TriangleQuadrature",
    "annulus_region",
    "apply_dirichlet_conditions",
    "apply_global_matrix",
    "apply_laplace_stiffness_matrix",
    "apply_mass_matrix",
    "apply_operator",
    "assemble_global_matrix",
    "assemble_laplace_stiffness_bcoo",
    "assemble_laplace_stiffness_matrix",
    "assemble_load_vector",
    "assemble_mass_bcoo",
    "assemble_mass_matrix",
    "boundary_nodes_from_coordinates",
    "benchmark_callable",
    "benchmark_local_fem_kernel",
    "benchmark_seed_equilibrium",
    "gaussian_coil_source",
    "linear_basis",
    "linear_basis_gradients",
    "linear_load_vector",
    "linear_mass_matrix",
    "linear_stiffness_matrix",
    "load_gs_mesh",
    "load_config",
    "mesh_from_arrays",
    "normalized_flux",
    "observed_rates",
    "polygon_region",
    "poisson_error_metrics",
    "rectangle_region",
    "reference_triangle_nodes",
    "save_gs_mesh",
    "sample_regions",
    "run_poisson_convergence_study",
    "sine_poisson_exact",
    "sine_poisson_forcing",
    "solve_dirichlet_system",
    "solve_fixed_boundary",
    "solve_from_config",
    "solve_sine_poisson",
    "solovev_source",
    "triangle_area",
    "triangle_jacobian",
    "triangle_quadrature",
    "unit_square_triangles",
]
